package com.klaye.monolith.audit.entity;

public enum AuditAction {
    CREER_DOSSIER,
    CREER_MISSION,
    CONSTITUER_EQUIPE,
    CONSULTER_DOCUMENT,
    TELECHARGER_DOCUMENT,
    SUPPRIMER_DOCUMENT,
    SUPPRIMER_DOSSIER,
    UPDATE_DOSSIER,
    UPLOAD_DOCUMENT,
    SUPPRIMER_MISSION,
    UPDATE_MISSION
}
