/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentResponse { 
    id?: string;
    nomFichierOriginal?: string;
    nomFichierStocke?: string;
    cheminStockage?: string;
    typeFichier?: string;
    taille?: number;
    createdAt?: string;
    downloadUrl?: string;
}

