/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserMissionResponse { 
    id?: number;
    userId?: number;
    missionId?: number;
    codeMission?: string;
    assignedBy?: number;
    assignedAt?: string;
}

